# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 126f00df6b03cc89d261362b2be235a810843fee7d0162810b876546cd46960de9a585bd69986bafc26574d02568bc056e31db1d7754ba82224a3ccbff37e624

test:
  secret_key_base: 57879337a4fbdc05d97e86e3eaaaf171597f8b72fb82f2e59e9353f711058926dc3cce7e48c64fe4569584af9abfc07230a13ea4c2264c00f5feae238464a116

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
